# Endlosschleife: Exportiert und synchronisiert alle Vertretungspläne im festen
# Intervall (Standard 30 Minuten). Die Verzeichnisse ../workspace (Projekt) und
# ../data (Archiv) werden in den Container gemountet.
services:
  vertretungsplan-runner:
    image: node:22-alpine
    working_dir: /workspace/tooling
    volumes:
      - ..:/workspace
      - ../data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: ["sh", "-c", "/workspace/tooling/scripts/docker-runner.sh"]
    env_file:
      - ./env/elternportal.env
      - ./env/icloud.env
